baseURL = "https://cocky-aryabhata-833924.netlify.com/"
languageCode = "en-us"
title = "My New Hugo Site"
relativeURLs = true
theme = "theme"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      footnote = true

[taxonomies]
  category = "categories"
  taxo = "taxos"
  tag = "tags"

[languages]
  [languages.en]
    contentDir = "content"
    languageName = "English"
    weight = 10
  [languages.la]
    contentDir = "lorem"
    languageName = "Latin"
    weight = 20